apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  selector:
    app: brain-tasks
  ports:
    - protocol: TCP
      port: 3000        # External port via LoadBalancer
      targetPort: 3000  # Matches containerPort
  type: LoadBalancer
